// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatikaDev_CodeFirst.DataModels;

namespace PatikaDev_CodeFirst.Migrations
{
    [DbContext(typeof(BaseEntity))]
    [Migration("20220129201028_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Assistant", b =>
                {
                    b.Property<int>("AssistantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssistantLastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AssistantName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AssistantID");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AttendanceStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("EducationToStudentID")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EducationToStudentID");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Education", b =>
                {
                    b.Property<int>("EducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EducationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationEnd")
                        .HasColumnType("int");

                    b.Property<string>("EducationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationStart")
                        .HasColumnType("int");

                    b.Property<int>("EducationWeeks")
                        .HasColumnType("int");

                    b.HasKey("EducationID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Educator", b =>
                {
                    b.Property<int>("EducatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EducationLastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EducatorName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EducatorID");

                    b.ToTable("Educators");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToAssistant", b =>
                {
                    b.Property<int>("EducationToAssistantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssistantID")
                        .HasColumnType("int");

                    b.Property<int?>("EducationID")
                        .HasColumnType("int");

                    b.HasKey("EducationToAssistantID");

                    b.HasIndex("AssistantID");

                    b.HasIndex("EducationID");

                    b.ToTable("EducationToAssistants");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToEducator", b =>
                {
                    b.Property<int>("EducationToEducatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EducationID")
                        .HasColumnType("int");

                    b.Property<int?>("EducatorID")
                        .HasColumnType("int");

                    b.HasKey("EducationToEducatorID");

                    b.HasIndex("EducationID");

                    b.HasIndex("EducatorID");

                    b.ToTable("EducationToEducators");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToStudent", b =>
                {
                    b.Property<int>("EducationToStudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EducationID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SuccesStatus")
                        .HasColumnType("int");

                    b.HasKey("EducationToStudentID");

                    b.HasIndex("EducationID");

                    b.HasIndex("StudentID");

                    b.ToTable("EducationToStudents");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentLastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.Attendance", b =>
                {
                    b.HasOne("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToStudent", "EducationToStudent")
                        .WithMany()
                        .HasForeignKey("EducationToStudentID");

                    b.Navigation("EducationToStudent");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToAssistant", b =>
                {
                    b.HasOne("PatikaDev_CodeFirst.DataModels.Assistant", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantID");

                    b.HasOne("PatikaDev_CodeFirst.DataModels.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationID");

                    b.Navigation("Assistant");

                    b.Navigation("Education");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToEducator", b =>
                {
                    b.HasOne("PatikaDev_CodeFirst.DataModels.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationID");

                    b.HasOne("PatikaDev_CodeFirst.DataModels.Educator", "Educator")
                        .WithMany()
                        .HasForeignKey("EducatorID");

                    b.Navigation("Education");

                    b.Navigation("Educator");
                });

            modelBuilder.Entity("PatikaDev_CodeFirst.DataModels.MiddleTable.EducationToStudent", b =>
                {
                    b.HasOne("PatikaDev_CodeFirst.DataModels.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationID");

                    b.HasOne("PatikaDev_CodeFirst.DataModels.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");

                    b.Navigation("Education");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
